### ISSUE TITLE
ERROR com.mrv.yangtools.codegen.main.Main - Error while generating Swagger

### ISSUE THREAD

**Issue by jyliu123** [Open-Network-Models-and-Interfaces-ONMI/TAPI#499]
When I use yang2aos.sh to convert a file in yang format to yaml format, I encounter the above error. I want to know whether the swagger-generator-cli-1.1.13-executable.jar used is open source. If it is open source, can you tell me which project it is? 

Generating OpenAPI files from YANG files
Generating ./OAS/nco-md-type-definitions.yaml
2020-09-28 21:03:39,983 [main] INFO  c.mrv.yangtools.common.ContextHelper - adding .\TMP
2020-09-28 21:03:40,081 [main] INFO  c.mrv.yangtools.common.SchemaBuilder - Inspecting all defined yangs [.\TMP\nco-md-type-definitions.yang]
2020-09-28 21:03:40,326 [main] INFO  com.mrv.yangtools.codegen.main.Main - Modules found in the ./TMP/ are nco-md-type-definitions
2020-09-28 21:03:40,403 [main] INFO  c.m.y.codegen.SwaggerGenerator - Generating swagger for yang modules: [nco-md-type-definitions]
2020-09-28 21:03:40,407 [main] WARN  c.m.y.codegen.SwaggerGenerator - Generated swagger has no definitions
2020-09-28 21:03:40,408 [main] ERROR com.mrv.yangtools.codegen.main.Main - Error while generating Swagger
java.lang.NullPointerException: null
        at com.mrv.yangtools.codegen.impl.postprocessor.SortComplexModels.accept(SortComplexModels.java:26)
        at com.mrv.yangtools.codegen.SwaggerGenerator.generate(SwaggerGenerator.java:277)
        at com.mrv.yangtools.codegen.main.Main.generate(Main.java:150)
        at com.mrv.yangtools.codegen.main.Main.main(Main.java:93)

**Comment by amazzini** [comment]
The project is https://github.com/bartoszm/yang2swagger

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
